x =int(input("x : "))
y =int(input("y : "))
print(x,"+",y,"=",x+y, ("บวก"))
print(x,"-",y,"=",x-y, ("ลบ"))
print(x,"*",y,"=",x*y, ("คูณ"))
print(x,"/",y,"=",x/y, ("หาร"))
print ("ผลที่ได้จะเป็นไปตามข้างต้น")
